/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CDDAFurniture = CDDAFurnitureCr | CDDAFurnitureBg;
export type CDDAIntRange = number | [number, number];
export type CDDAColor = string | string[];
export type CDDAVolume = number | string;
export type CDDAName = string | CDDATranslation;
export type CDDAMass = number | string;
export type ArrayOf_CDDAFurniture = CDDAFurniture[];

export interface CDDAFurnitureCr {
  bash?: CDDAFurnBash | null;
  bonus_fire_warmth_feet?: number;
  close?: string;
  color: CDDAColor;
  comfort?: number;
  connects_to?: string[];
  coverage?: number;
  crafting_pseudo_item?: string;
  deconstruct?: CDDAFurnDecon | null;
  description: string;
  examine_action?: string;
  flags?: string[];
  floor_bedding_warmth?: number;
  id: string;
  light_emitted?: number;
  looks_like?: string;
  map_bash_info?: string;
  max_volume?: CDDAVolume | null;
  move_cost_mod: number;
  name: CDDAName;
  open?: string;
  plant_data?: CDDAFurnPlant | null;
  required_str: number;
  surgery_skill_multiplier?: number;
  symbol: string;
  type: string;
  workbench?: CDDAFurnWorkbench | null;
  [k: string]: unknown;
}
export interface CDDAFurnBash {
  bash_below?: boolean;
  collapse_radius?: number;
  destroy_only?: boolean;
  explosive?: number;
  furn_set?: string;
  items?: CDDABashDeconItem[];
  sound?: string;
  sound_fail?: string;
  sound_fail_vol?: number;
  sound_vol?: number;
  str_max?: number;
  str_max_blocked?: number;
  str_max_supported?: number;
  str_min?: number;
  str_min_blocked?: number;
  str_min_supported?: number;
  tent_centers?: string[];
  [k: string]: unknown;
}
export interface CDDABashDeconItem {
  charges?: CDDAIntRange | null;
  count?: CDDAIntRange | null;
  item: string;
  prob?: number;
  [k: string]: unknown;
}
export interface CDDAFurnDecon {
  can_do?: boolean;
  deconstruct_above?: boolean;
  furn_set?: string;
  items?: CDDABashDeconItem[];
  [k: string]: unknown;
}
export interface CDDATranslation {
  [k: string]: unknown;
}
export interface CDDAFurnPlant {
  base: string;
  growth_multiplier: number;
  harvest_multiplier: number;
  transform: string;
  [k: string]: unknown;
}
export interface CDDAFurnWorkbench {
  mass: CDDAMass;
  multiplier: number;
  volume: CDDAVolume;
  [k: string]: unknown;
}
export interface CDDAFurnitureBg {
  bash?: CDDAFurnBash | null;
  bgcolor: CDDAColor;
  bonus_fire_warmth_feet?: number;
  close?: string;
  comfort?: number;
  connects_to?: string[];
  coverage?: number;
  crafting_pseudo_item?: string;
  deconstruct?: CDDAFurnDecon | null;
  description: string;
  examine_action?: string;
  flags?: string[];
  floor_bedding_warmth?: number;
  id: string;
  light_emitted?: number;
  looks_like?: string;
  map_bash_info?: string;
  max_volume?: CDDAVolume | null;
  move_cost_mod: number;
  name: CDDAName;
  open?: string;
  plant_data?: CDDAFurnPlant | null;
  required_str: number;
  surgery_skill_multiplier?: number;
  symbol: string;
  type: string;
  workbench?: CDDAFurnWorkbench | null;
  [k: string]: unknown;
}
