// AUTO-GENERATED by typescript-type-def

export default types;
export namespace types{
export type CDDATranslation={};
export type CDDAName=(string|types.CDDATranslation);
export type I64=number;
export type F64=number;
export type CDDAMass=(types.I64|string);
export type CDDAVolume=(types.I64|string);
export type CDDAFurnWorkbench={"multiplier":types.F64;"mass":types.CDDAMass;"volume":types.CDDAVolume;};
export type CDDAFurnPlant={"transform":string;"base":string;"growth_multiplier":types.F64;"harvest_multiplier":types.F64;};
export type CDDAIntRange=(types.I64|[types.I64,types.I64]);
export type CDDABashDeconItem={"item":string;"count":(types.CDDAIntRange|null);"charges":(types.CDDAIntRange|null);"prob"?:types.I64;};
export type CDDAFurnBash={"str_min"?:types.I64;"str_max"?:types.I64;"str_min_blocked"?:types.I64;"str_max_blocked"?:types.I64;"str_min_supported"?:types.I64;"str_max_supported"?:types.I64;"explosive"?:types.I64;"sound_vol"?:types.I64;"sound_fail_vol"?:types.I64;"collapse_radius"?:types.I64;"destroy_only"?:boolean;"bash_below"?:boolean;"sound"?:string;"sound_fail"?:string;"furn_set"?:string;"tent_centers"?:(string)[];"items"?:(types.CDDABashDeconItem)[];};
export type CDDAFurnDecon={"deconstruct_above"?:boolean;"can_do"?:boolean;"furn_set"?:string;"items"?:(types.CDDABashDeconItem)[];};
export type CDDAFurnitureBase={"type":string;"id":string;"name":types.CDDAName;"description":string;"symbol":string;"move_cost_mod":types.I64;"required_str":types.I64;"light_emitted"?:types.I64;"coverage"?:types.I64;"crafting_pseudo_item"?:string;"workbench"?:types.CDDAFurnWorkbench;"plant_data"?:types.CDDAFurnPlant;"surgery_skill_multiplier"?:types.F64;"looks_like"?:string;"examine_action"?:string;"bash"?:types.CDDAFurnBash;"map_bash_info"?:string;"deconstruct"?:types.CDDAFurnDecon;"close"?:string;"open"?:string;"max_volume"?:types.CDDAVolume;"flags"?:(string)[];"connects_to"?:(string)[];"comfort"?:types.I64;"floor_bedding_warmth"?:types.I64;"bonus_fire_warmth_feet"?:types.I64;};
export type CDDAColor=(string|(string)[]);
export type CDDAFurnitureCr=(types.CDDAFurnitureBase&{"color":types.CDDAColor;});
export type CDDAFurnitureBg=(types.CDDAFurnitureBase&{"bgcolor":types.CDDAColor;});
export type CDDAFurniture=(types.CDDAFurnitureCr|types.CDDAFurnitureBg);
}
