/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CDDAModInfoAuthors =
  | {
      Name: string;
    }
  | {
      NameList: string[];
    };
export type CDDAModInfoCategory =
  | "content"
  | "total_conversion"
  | "items"
  | "creatures"
  | "misc_additions"
  | "buildings"
  | "vehicles"
  | "rebalance"
  | "magical"
  | "item_exclude"
  | "monster_exclude"
  | "graphical";
export type MOD_INFO_Literal = "MOD_INFO";
export type ArrayOf_CDDAModInfo = CDDAModInfo[];

/**
 * @docs https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/MODDING.md#modinfojson
 */
export interface CDDAModInfo {
  "//"?: string;
  authors?: CDDAModInfoAuthors | null;
  category?: CDDAModInfoCategory | null;
  dependencies?: string[] | null;
  description: string;
  id: string;
  maintainers?: string[] | null;
  name: string;
  type: MOD_INFO_Literal;
  version?: string | null;
  [k: string]: unknown;
}
