// AUTO-GENERATED by typescript-type-def

export default types;
export namespace types{
export type I64=number;
export type CDDAPaletteDistributionMixed=(string|[string,types.I64]);
export type CDDAPaletteDistribution=(string|(string)[]|[string,types.I64]|(types.CDDAPaletteDistributionMixed)[]);
export type CDDAPaletteTerrainValueParameterReference={"param":string;"fallback":string;};
export type CDDAPaletteTerrainValue=(string|types.CDDAPaletteDistribution|types.CDDAPaletteTerrainValueParameterReference);
export type CDDAPaletteParametersValueDefault={"distribution":types.CDDAPaletteDistribution;};
export type CDDAPaletteParametersValue={"type":string;"default":types.CDDAPaletteParametersValueDefault;};
export type CDDAPaletteFurnitureValue=(string|types.CDDAPaletteDistribution);
export type CDDAPaletteLiquidsValue={"liquid":string;"amount":[types.I64,types.I64];};
export type CDDAIntRange=(types.I64|[types.I64,types.I64]);
export type CDDAPaletteItemsValueItem={"item":string;"chance":types.I64;"repeat"?:types.CDDAIntRange;"ammo"?:types.I64;"magazine"?:types.I64;};
export type CDDAPaletteItemValue=(types.CDDAPaletteItemsValueItem|(types.CDDAPaletteItemsValueItem)[]);
export type F64=number;
export type CDDAPaletteMonstersValue={"monster":string;"chance":types.I64;"pubdensity"?:types.F64;};
export type CDDAPalette={"type":string;"id":string;"terrain":Record<string,types.CDDAPaletteTerrainValue>;"//"?:string;"parameters"?:Record<string,types.CDDAPaletteParametersValue>;
/**
 * * @example "toilets": { "&": { "amount": [ 0, 40 ] } }
 *    
 */
"toilets"?:Record<string,Record<string,(types.I64)[]>>;
/**
 * * @example "furniture": { "c": "f_exercise", "u": [ "f_ergometer", "f_ergometer_mechanical" ]}
 *    
 */
"furniture"?:Record<string,types.CDDAPaletteFurnitureValue>;"liquids"?:Record<string,types.CDDAPaletteLiquidsValue>;"items"?:Record<string,types.CDDAPaletteItemValue>;"monsters"?:Record<string,(types.CDDAPaletteMonstersValue)[]>;};
}
