// AUTO-GENERATED by typescript-type-def

export default types;
export namespace types{
export type I64=number;
export type CDDAPaletteDistributionMixed=(string|[string,types.I64]);
export type CDDAPaletteDistribution=(string|(string)[]|[string,types.I64]|(types.CDDAPaletteDistributionMixed)[]);
export type CDDAPaletteTerrainValueParameterReference={"param":string;"fallback":string;};
export type CDDAPaletteTerrainValue=(string|types.CDDAPaletteDistribution|types.CDDAPaletteTerrainValueParameterReference);
export type CDDAPaletteParametersValueDefault={"distribution":types.CDDAPaletteDistribution;};
export type CDDAPaletteParametersValue={"type":string;"default":types.CDDAPaletteParametersValueDefault;};
export type CDDAPaletteFurnitureValue=(string|types.CDDAPaletteDistribution);
export type CDDAPaletteLiquidsValue={"liquid":string;"amount":[types.I64,types.I64];};
export type CDDAPaletteItemsValueItem={"item":string;"chance":types.I64;"repeat":([types.I64,types.I64]|null);"ammo":(types.I64|null);"magazine":(types.I64|null);};
export type CDDAPaletteItemValue=(types.CDDAPaletteItemsValueItem|(types.CDDAPaletteItemsValueItem)[]);
export type CDDAPaletteMonstersValue={"monster":string;"chance":types.I64;};
export type CDDAPalette={"type":string;"id":string;"terrain":Record<string,types.CDDAPaletteTerrainValue>;"//":(string|null);"parameters":(Record<string,types.CDDAPaletteParametersValue>|null);
/**
 * * @example "toilets": { "&": { "amount": [ 0, 40 ] } }
 *    
 */
"toilets":(Record<string,Record<string,(types.I64)[]>>|null);"furniture":(Record<string,types.CDDAPaletteFurnitureValue>|null);"liquids":(Record<string,types.CDDAPaletteLiquidsValue>|null);"items":(Record<string,types.CDDAPaletteItemValue>|null);"monsters":(Record<string,(types.CDDAPaletteMonstersValue)[]>|null);};
}
