/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Type root for json schema export, in this way we can export all types together
 */
export type EventRootObject = ModLoadingEventPayload;

/**
 * game://mod-loading
 */
export interface ModLoadingEventPayload {
  fileList: ModLoadingEventFileItem[];
  /**
   * This is the type of this event, won't have actuarial data, just sync this string between rs and ts
   */
  "game://mod-loading"?: string | null;
  [k: string]: unknown;
}
export interface ModLoadingEventFileItem {
  file_count: number;
  mod_name: string;
  progress: number;
  [k: string]: unknown;
}
