/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CDDATerrain = CDDATerFurnCommonOptional | CDDATerFurnCommonMandatory;
export type CDDAName = string | CDDATranslation;
export type ArrayOf_CDDATerrain = CDDATerrain[];

export interface CDDATerFurnCommonOptional {
  "copy-from": string;
  description?: string;
  name?: CDDAName;
  [k: string]: unknown;
}
export interface CDDATranslation {
  aaa: string;
  [k: string]: unknown;
}
export interface CDDATerFurnCommonMandatory {
  description: string;
  name: CDDAName;
  [k: string]: unknown;
}
