/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CDDATerrain = CDDATerFurnSymbolInd | CDDATerFurnSymbolRely;
export type CDDATerFurnSymbolInd =
  | {
      color: CDDATerFurnColor;
      [k: string]: unknown;
    }
  | {
      bgcolor: CDDATerFurnColor;
      [k: string]: unknown;
    };
export type CDDATerFurnColor = string | string[];
export type CDDATerFurnSymbolRely =
  | {
      color: CDDATerFurnColor;
      [k: string]: unknown;
    }
  | {
      bgcolor: CDDATerFurnColor;
      [k: string]: unknown;
    };
export type ArrayOf_CDDATerrain = CDDATerrain[];
