// AUTO-GENERATED by typescript-type-def

export default types;
export namespace types{
export type I64=number;
export type F64=number;
export type CDDAMapgenPlaceMonster={"monster":string;"x":types.I64;"y":types.I64;"density":types.F64;"repeat":(types.I64)[];};
export type I32=number;
export type CDDAMapgenTerrainRandomListItem=(string|[string,types.I32]);
export type CDDAMapgenTerrain=(string|(types.CDDAMapgenTerrainRandomListItem)[]);
export type CDDAMapgenFurniture=(string|(string)[]);
export type CDDAMapgenPlaceLoot={"item":string;"x":types.I64;"y":types.I64;"chance":types.I64;};
export type CDDAMapgenItemRandomListItem={"item":string;"chance":types.I64;"repeat":((types.I64)[]|null);};
export type CDDAMapgenItem=(string|types.CDDAMapgenItemRandomListItem|(types.CDDAMapgenItemRandomListItem)[]);
export type CDDAMapgenObject={"fill_ter":string;"rows":(string)[];"palettes"?:(string)[];"place_monsters"?:(types.CDDAMapgenPlaceMonster)[];
/**
 * * @example `{ "_": "t_open_air", ")": "t_wall_glass", "#": "t_rock_wall", "-": "t_floor", "]": "t_door_glass_c" }`
 *    
 */
"terrain":Record<string,types.CDDAMapgenTerrain>;
/**
 * * @example `{ "=": "f_magic_bench", "-": "f_alembic", "?": "f_rack_wood" }`
 *    
 */
"furniture":(Record<string,types.CDDAMapgenFurniture>|null);"place_loot"?:(types.CDDAMapgenPlaceLoot)[];"items":(Record<string,types.CDDAMapgenItem>|null);
/**
 * * @example `{ "=": "tr_rollmat" }`
 *    
 */
"traps":(Record<string,string>|null);};
export type CDDAMapgen={"type":string;"method":string;"om_terrain":string;"object":types.CDDAMapgenObject;};
export type CDDAMapgenWithCache={
/**
 * * Full mapgen file content, for code editor to display
 *    
 */
"rawMapgen":(types.CDDAMapgen)[];
/**
 * * Map 2D array that have place-holder characters replaced with actual item ID, for map view to display
 *    * And we have multiple mapgen in a file, so this will be a 3D array
 *    
 */
"parsedMap":(((string)[])[])[];};
}
